### ISSUE TITLE
invalid-id is not a valid identifier

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/Binding.scala#21]
This bug occures in 10.0.0-M3

``` scala
@dom def invalidId = {
  <div id="invalid-id"></div>
}
```

```
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[IllegalArgumentException: requirement failed: invalid-id is not a valid identifier]
    at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
    at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
    at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
    at play.sbt.run.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
Caused by: java.lang.IllegalArgumentException: requirement failed: invalid-id is not a valid identifier
    at scala.Predef$.require(Predef.scala:233) ~[scala-library.jar:na]
    at org.scalajs.core.ir.Trees$.requireValidIdent(Trees.scala:61) ~[na:na]
    at org.scalajs.core.ir.Trees$Ident.<init>(Trees.scala:45) ~[na:na]
    at org.scalajs.core.compiler.JSEncoding$class.encodeLocalSym(JSEncoding.scala:188) ~[na:na]
    at org.scalajs.core.compiler.GenJSCode.encodeLocalSym(GenJSCode.scala:31) ~[na:na]
    at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1589) ~[na:na]
    at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:1529) ~[na:na]
    at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$70.apply(GenJSCode.scala:2714) ~[na:na]
    at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$70.apply(GenJSCode.scala:2714) ~[na:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
```

**Comment by Atry** [comment]
Fixed in 		5a879e8
