### ISSUE TITLE
scalafmt fails when using html 

### ISSUE THREAD

**Issue by visox** [ThoughtWorksInc/Binding.scala#29]
```
object Something {

  @dom
  def apply(user: Var[Option[User]], logoutCall: () => Unit): Binding[Div] = {
<div>
{
   user.bind match {
      case None =>
         <div/>
      case Some(_) =>
         <a class = "btn btn-secondary" style = "float:right;" onclick = { (e: Event) ⇒ logoutCall() }>
            Logout
         </a>
     }
   }
</div>
}
```

in terminal
`>`scalafmt
[trace] Stack trace suppressed: run last web-client/compile:scalafmt for the full output.
[error] (web-client/compile:scalafmt) java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected

`>`last web-client/compile:scalafmt
java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected
	at scala.meta.internal.tokenizers.LegacyScanner.getXml(LegacyScanner.scala:959)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchLT$1(LegacyScanner.scala:336)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:344)
	at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:233)
	at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1022)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:154)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:34)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:263)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:23)
	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:12)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:207)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:207)
	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:168)
	at scala.meta.internal.parsers.ScalametaParser$$anon$201.apply(ScalametaParser.scala:3650)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
	at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:51)
	at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:46)
	at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:85)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:76)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (web-client/compile:scalafmt) java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected

**Comment by Atry** [comment]
Looks like an issue in scalafmt. Please submit this issue at https://github.com/olafurpg/scalafmt/issues

**Comment by visox** [comment]
ok thx
