### ISSUE TITLE
unable to use @fxml with a java bean when defined in the same project

### ISSUE THREAD

**Issue by jfilali** [ThoughtWorksInc/Binding.scala#41]
I tried this : 

```
class CustomTag(){
  @BeanProperty var field : String = ""
  override def toString = s"Person: $field"
}

@JSExport
object Foo {
  @fxml def test() = { <CustomTag field="test"/> }
}
```

[error] java.lang.ClassNotFoundException: sth.pkg.CustomTag
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:264)
[error]         at com.thoughtworks.binding.fxml$Macros.resolvePropertiesForJavaBean(fxml.scala:928)
[error]   @fxml def test() = { <CustomTag field="test"/> }

I tried 

```
class CustomTag(@BeanProperty var field:String){
  override def toString = s"Person: $field"
}
```

sth.pkg.CustomTag is not a Java Bean nor a type built from JavaFXBuilderFactory
[error]   @fxml def test() = { <CustomTag field="test"/> }
[error]                         ^

I also tried to create a regular java class : 

```
public class CustomTag {
    private String field;
    public CustomTag(){

    }

    public CustomTag(String field){
        this.field=field;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
```

and get  java.lang.ClassNotFoundException:

I also tried to add an import next to it :

```
  @fxml def test() = {
      import sth.pkg.CustomTag


```

**Comment by jfilali** [comment]
The current workaround is to simply compile the tags inside another project. Using a shared project doesn't work though.
