### ISSUE TITLE
@fxml hangs after javafx has run in-JVM

### ISSUE THREAD

**Issue by nafg** [ThoughtWorksInc/Binding.scala#50]
To reproduce:

1. Go to https://gist.github.com/nafg/b51c7a9c1c8022ba3ac5f2a45eb1d62d and click Download ZIP, extract into a new directory.
2. Go into the directory and type `sbt run clean compile`
3. When the little window appears, close it.
4. The next compilation (forced because of the `clean`) hangs with this stack trace:

```
[error] /tmp/fxml/FxmlSample.scala:10: exception during macro expansion: 
[error] java.lang.InterruptedException
[error] 	at java.lang.Object.wait(Native Method)
[error] 	at java.lang.Object.wait(Object.java:502)
[error] 	at com.thoughtworks.binding.fxml$Macros$.<init>(fxml.scala:555)
[error] 	at com.thoughtworks.binding.fxml$Macros$.<clinit>(fxml.scala)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformXmlValue$1.applyOrElse(fxml.scala:1228)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformXmlValue$1.applyOrElse(fxml.scala:1219)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
[error] 	at com.thoughtworks.Extractor$PartialFunctionToExtractor$$anon$3.unapply(Extractor.scala:98)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$expand$1.applyOrElse(fxml.scala:1415)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$expand$1.applyOrElse(fxml.scala:1414)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
[error] 	at com.thoughtworks.Extractor$PartialFunctionToExtractor$$anon$3.unapply(Extractor.scala:98)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformBlock$1$$anonfun$37.apply(fxml.scala:1427)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformBlock$1$$anonfun$37.apply(fxml.scala:1425)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:327)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformBlock$1.applyOrElse(fxml.scala:1425)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer$$anonfun$com$thoughtworks$binding$fxml$Macros$XmlTransformer$$transformBlock$1.applyOrElse(fxml.scala:1423)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
[error] 	at com.thoughtworks.Extractor$PartialFunctionToExtractor$$anon$3.unapply(Extractor.scala:98)
[error] 	at com.thoughtworks.binding.fxml$Macros$XmlTransformer.transform(fxml.scala:1445)
[error] 	at com.thoughtworks.binding.fxml$Macros$$anonfun$macroTransform$1.apply(fxml.scala:1484)
[error] 	at com.thoughtworks.binding.fxml$Macros$$anonfun$macroTransform$1.apply(fxml.scala:1465)
[error] 	at com.thoughtworks.sde.core.Preprocessor.replaceDefBody(Preprocessor.scala:35)
[error] 	at com.thoughtworks.binding.fxml$Macros.macroTransform(fxml.scala:1464)
```

**Comment by Atry** [comment]
Still cannot reproduce for me.

There is no hanging for me.
However, it seems JVM crashes on my macOS environment:

```
$ sbt run clean compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from /Users/twer/.sbt/0.13/plugins
[info] Loading project definition from /private/tmp/xx/b51c7a9c1c8022ba3ac5f2a45eb1d62d/project
[info] Set current project to b51c7a9c1c8022ba3ac5f2a45eb1d62d (in build file:/private/tmp/xx/b51c7a9c1c8022ba3ac5f2a45eb1d62d/)
[info] Running FxmlSample 
May 26, 2017 1:31:28 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "com/sun/javafx/scene/control/skin/modena/modena.css" not found.
[success] Total time: 4 s, completed May 26, 2017 1:31:31 PM
[success] Total time: 0 s, completed May 26, 2017 1:31:31 PM
[info] Updating {file:/private/tmp/xx/b51c7a9c1c8022ba3ac5f2a45eb1d62d/}b51c7a9c1c8022ba3ac5f2a45eb1d62d...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/xx/b51c7a9c1c8022ba3ac5f2a45eb1d62d/target/scala-2.11/classes...
Java has been detached already, but someone is still trying to use it at -[GlassApplication applicationWillHide:]:/HUDSON/jfx/workspace/8u102/label/macosx-universal-92/rt/modules/graphics/src/main/native-glass/mac/GlassApplication.m:307
0   libglass.dylib                      0x000000011bd8e2a5 -[GlassApplication applicationWillHide:] + 117
1   CoreFoundation                      0x00007fffa1dc845c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
2   CoreFoundation                      0x00007fffa1dc835b _CFXRegistrationPost + 427
3   CoreFoundation                      0x00007fffa1dc80c2 ___CFXNotificationPost_block_invoke + 50
4   CoreFoundation                      0x00007fffa1d85523 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
5   CoreFoundation                      0x00007fffa1d8455c _CFXNotificationPost + 604
6   Foundation                          0x00007fffa37a9907 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
7   AppKit                              0x00007fff9fce1d55 -[NSApplication _doHideMaybeFakingIt:] + 260
8   AppKit                              0x00007fff9fa2f73e _hideShowHandler + 147
9   HIToolbox                           0x00007fffa12ebd85 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1708
10  HIToolbox                           0x00007fffa12eaff6 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 428
11  HIToolbox                           0x00007fffa1300d14 SendEventToEventTarget + 40
12  AppKit                              0x00007fff9f8ad1c4 _DPSNextEvent + 3024
13  AppKit                              0x00007fffa00287ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
14  AppKit                              0x00007fff9f8a13db -[NSApplication run] + 926
15  libosxapp.dylib                     0x000000011b00b14d +[NSApplicationAWT runAWTLoopWithApp:] + 156
16  libawt_lwawt.dylib                  0x0000000123fba4b3 -[AWTStarter starter:] + 905
17  Foundation                          0x00007fffa38147ba __NSThreadPerformPerform + 326
18  CoreFoundation                      0x00007fffa1dd2321 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
19  CoreFoundation                      0x00007fffa1db321d __CFRunLoopDoSources0 + 557
20  CoreFoundation                      0x00007fffa1db2716 __CFRunLoopRun + 934
21  CoreFoundation                      0x00007fffa1db2114 CFRunLoopRunSpecific + 420
22  java                                0x0000000109b37465 CreateExecutionEnvironment + 871
23  java                                0x0000000109b3318c JLI_Launch + 1952
24  java                                0x0000000109b394c2 main + 101
25  java                                0x0000000109b329e4 start + 52
26  ???                                 0x000000000000000a 0x0 + 10
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011bd8e304, pid=94872, tid=0x0000000000000307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libglass.dylib+0x5304]  -[GlassApplication applicationWillHide:]+0xd4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /private/tmp/xx/b51c7a9c1c8022ba3ac5f2a45eb1d62d/hs_err_pid94872.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/usr/local/Cellar/sbt/0.13.15/libexec/bin/sbt-launch-lib.bash: line 46: 94872 Abort trap: 6           "$@"
```

**Comment by nafg** [comment]
I'm on Ubuntu. Maybe it's something about the X11 implementation? Can you try in a VM?

**Comment by nafg** [comment]
Anyway it looks like the same basic issue, but the mac implementation asserts about it and the linux implementation proceeds resulting in the hang?

**Comment by Atry** [comment]
I guess the two problems are irrelevant
